{% set version = "1.4.9" %}

package:
    name: amqp
    version: {{ version }}

source:
    fn: amqp-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/a/amqp/amqp-{{ version }}.tar.gz
    md5: df57dde763ba2dea25b3fa92dfe43c19

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - amqp

about:
    home: http://github.com/celery/py-amqp
    license: BSD 3-clause
    license_family: BSD
    license_file: LICENSE
    summary: Low-level AMQP client for Python (fork of amqplib)

extra:
    recipe-maintainers:
        - anguslees
        - kwilcox
        - frol
