# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lyDgYSsgZxAZ95XkF6oBpCUmNctvSyJSxTYyYF0gAnb9fbqroExglnDzOL0gy6e7Gi1NgI12hjtqtB7tmBU8srnZIu1+SUjYthura7qjDhNllo6ipwV2O0/aO5G2jPk9QZNAVl5vNJCANeVYBhq8CCS69paCrn8wSJXwN3ovKotXepAq1oAfnTz4iHtxRGTYfpfT3MIQqueFI6+WV3GHyZX/gSG7EMI3DSFVHKaCNnWsRrBmYmH20KfQdSQSq6DZIEJIGQIVeV7qc73zKdJAzuSuxuHVSg6zNDcddok8MM46YBiVw7YAinfXAevUi178iabiZz3Nato0mMLX/qToD6GX+qHjMo9Azs3RXmTs/9Gqz2Vtnk+wkDSG0nWFbxubYn9MgVhKkS6FMUmBrD9oNNQ50+j4Ej/Q8aWEjzRv+MsQuPPqyUh/BR7+JuDwKQPRXnJYOnUZFH0wiU2cU6Gauc3u60MTalsVBn5w4RD9epYjIGMCSC3VMKoFnoXvM+eK9kZxgefBjggwZPMGyn9WfeTdVEIeJxV4PfS24gmOKlNaNHEvb8vcqU/yS1Z0XvOKHz/TWhMuKPPHfgKhCQLCg7vDydOjzLY/jEGxhmcONNZs7OqqTfFUB/xM+ZUO3lhYyz7DmVdF2UPS7JUL4wkof0agSZcAh8oUjVByK84JEGU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
